library(sqldf)
db <- read.csv.sql("household_power_consumption.txt", sql = "select * from file where Date = '1/2/2007' or Date = '2/2/2007' ", header = TRUE, sep = ";")
db$datetime <- strptime(paste(db$Date, db$Time), "%d/%m/%Y %H:%M:%S")
png("plot3.png", width = 480, height = 480)
plot(db$datetime, db$Sub_metering_1, xlab = "", ylab = "Energy sub metering", type = "n")
lines(db$datetime, db$Sub_metering_1, type = "l")
lines(db$datetime, db$Sub_metering_2, type = "l", col = "red")
lines(db$datetime, db$Sub_metering_3, type = "l", col = "blue")
legend("topright",lty = 1, col = c("black","red","blue"), legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()