library(sqldf)
db <- read.csv.sql("household_power_consumption.txt", sql = "select * from file where Date = '1/2/2007' or Date = '2/2/2007' ", header = TRUE, sep = ";")
db$datetime <- strptime(paste(db$Date, db$Time), "%d/%m/%Y %H:%M:%S")
png("plot2.png", width = 480, height = 480)
plot(db$datetime, db$Global_active_power, xlab = "", ylab = "Global Active Power (kilowatts)", type = "n")
lines(db$datetime, db$Global_active_power, type = "l")
dev.off()